"""Add position field

Revision ID: 0f846b00d0db
Revises: f0c6a1421c2d
Create Date: 2020-09-29 18:40:51.646237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f846b00d0db'
down_revision = 'f0c6a1421c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_node', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_node', 'position')
    # ### end Alembic commands ###
