"""Added token expiry table

Revision ID: 8e66726dca68
Revises: 99f6435d71b5
Create Date: 2020-09-24 21:20:55.777212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e66726dca68'
down_revision = '99f6435d71b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_grave',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_grave')
    # ### end Alembic commands ###
