"""Added timeline tables

Revision ID: 99f6435d71b5
Revises: ba60952fdb89
Create Date: 2020-09-24 00:14:34.870719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f6435d71b5'
down_revision = 'ba60952fdb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('timeline_node',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['timeline_id'], ['timeline.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_node')
    op.drop_table('timeline')
    # ### end Alembic commands ###
