"""Remove revoked token tables

Revision ID: f0c6a1421c2d
Revises: a7c6975cb343
Create Date: 2020-09-28 19:25:06.955488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0c6a1421c2d'
down_revision = 'a7c6975cb343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='revoked_token_pkey')
    )
    # ### end Alembic commands ###
